server:
  port: 8090

spring:
  application:
    name: payment-project
  # 1. Database Connection (Service name: db)
  datasource:
    url: jdbc:postgresql://localhost:5432/payments_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  
  # 2. Redis Connection (Service name: redis)
  data:
    redis:
      host: localhost
      port: 6379
  
  # 3. Kafka Connection (Service name: kafka_custom)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest

  # 4. Mail Properties
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 0c7394032e8e9d
    password: e63b86187cd740
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true # This corresponds to 'tls = yes'

# 5. Observability (For Prometheus/Grafana)
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    prometheus:
      enabled: true

# 6. Logging
logging:
  level:
    org.apache.kafka.common.config.AbstractConfig: WARN
    org.apache.kafka.clients.consumer.ConsumerConfig: WARN
    org.apache.kafka.clients.producer.ProducerConfig: WARN

app:
  scheduling:
    replay-cron: "0 */10 * * * *" # Every 1 minute for testing